name: Fly Deploy
on:
  workflow_run:
    workflows:
      - "Static Analysis and Report"
    types:
      - completed

jobs:
  verify-triggering-workflow:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Verify the triggering workflow passed
        run: echo 'The triggering workflow passed'

  build:
    name: Build Docker image
    runs-on: ubuntu-latest
    needs: verify-triggering-workflow
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and export Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: is-in-bible-br:latest
          outputs: type=docker,dest=/tmp/is-in-bible-br.tar

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v3
        with:
          name: is-in-bible-br
          path: /tmp/is-in-bible-br.tar

  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group    # optional: ensure only one action runs at a time
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Download Docker image artifact
        uses: actions/download-artifact@v3
        with:
          name: is-in-bible-br
          path: /tmp

      - name: Load Docker image
        run: |
          docker load --input /tmp/is-in-bible-br.tar

      - name: Deploy with Flyctl
        run: flyctl deploy --image is-in-bible-br --debug
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
